tools: argsfilter: install sources to /usr/src/opae/argsfilter
OPAE/opae-sdk pull request #2050
Opened 2021-05-25 08:11 UTC by hundeboll-silicom

Building samples installed with the opae-devel package requires access to
the argsfilter header and source, so include those in said package.

Signed-off-by: Martin Hundebøll <mhu@silicom.dk>

2021-05-25 21:41 UTC, tswhison requested changes
But, remember the Fedora rule not to package static libraries?

2021-05-27 07:32 UTC, hundeboll-silicom commented
> But, remember the Fedora rule not to package static libraries?

Which is why I package the source (`argsfilter.c` and `argsfilter.h`) in `/usr/src/opae/argsfilter`... That way one can build the samples with:

```
$ gcc -I /usr/src/opae/argsfilter/ \
        /usr/src/opae/argsfilter/argsfilter.c \
        /usr/src/opae/samples/hello_fpga/hello_fpga.c \
        -l opae-c -l uuid
```

2021-05-27 21:23 UTC, tswhison approved these changes
Ah yes.. Thanks!

2021-06-10 14:36 UTC, anandaravuri approved these changes

2021-06-10 17:13 UTC, michelleyho approved these changes

2021-06-11 20:39 UTC, merged