Update fpgainfo events to latest register specs
OPAE/opae-sdk pull request #2372
Opened 2021-11-11 08:14 UTC by sc-ele

Update fpgainfo events to latest register specs

2021-11-11 17:42 UTC, tswhison requested changes

2021-11-11 17:42 UTC, tswhison commented on tools/libboard/board_n6000/board_event_log.c
> +	UNUSED_PARAM(p);  // Need dummy paramater to cheat the coding style check!
Please don't do this.  The coding style check is there for a reason.  What is the issue?

2021-11-11 17:42 UTC, tswhison commented on tools/libboard/board_n6000/board_event_log.c
> +	UNUSED_PARAM(p);  // Need dummy paramater to cheat the coding style check!
Please don't do this.  Why is the coding style check being subverted?

2021-11-12 04:45 UTC, sc-ele commented
In the calls to these functions, I wanted to align the value parameter in the same column as the surrounding calls as it looks much nicer and helps with readability. Coding style check complains about this, it does not allow spaces where I put a dummy NULL parameter. It does not understand esthetics.

Sure, I can change it to the ugly look if you insist.

/Esa
________________________________
From: Tim Whisonant ***@***.***>
Sent: Thursday, November 11, 2021 18:42
To: OPAE/opae-sdk ***@***.***>
Cc: Esa Erkki Leskinen ***@***.***>; Author ***@***.***>
Subject: Re: [OPAE/opae-sdk] Update fpgainfo events to latest register specs (PR #2372)

Caution: This is an external email. Please take care when clicking links or opening attachments.


@tswhison requested changes on this pull request.

________________________________

In tools/libboard/board_n6000/board_event_log.c<https://github.com/OPAE/opae-sdk/pull/2372#discussion_r747697485>:

> @@ -218,6 +219,27 @@ static void bel_print_header(const char *label, struct bel_header *header)
        printf("  " BEL_LABEL_FMT "%s", 50, label, time_str);
 }

+static void reserved_field(void *p, uint32_t value, size_t first, size_t last)
+{
+       UNUSED_PARAM(p);  // Need dummy paramater to cheat the coding style check!


Please don't do this. The coding style check is there for a reason. What is the issue?

________________________________

In tools/libboard/board_n6000/board_event_log.c<https://github.com/OPAE/opae-sdk/pull/2372#discussion_r747697767>:

> @@ -218,6 +219,27 @@ static void bel_print_header(const char *label, struct bel_header *header)
        printf("  " BEL_LABEL_FMT "%s", 50, label, time_str);
 }

+static void reserved_field(void *p, uint32_t value, size_t first, size_t last)
+{
+       UNUSED_PARAM(p);  // Need dummy paramater to cheat the coding style check!
+
+       uint32_t mask = UINT_MAX >> (32 - (last - first));
+       uint32_t field = (value >> first) & mask;
+
+       if (field != 0)
+               printf("      *** RESERVED FIELD [%lu:%lu] IS NOT ZERO: 0x%X\n", last - 1, first, field);
+}
+
+static void reserved_bit(void *p, uint32_t value, size_t offset)
+{
+       UNUSED_PARAM(p);  // Need dummy paramater to cheat the coding style check!


Please don't do this. Why is the coding style check being subverted?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/OPAE/opae-sdk/pull/2372#pullrequestreview-804061068>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ASQR2UMX4WU4SWR6RVHVOLDULP6AJANCNFSM5HZ3FUXA>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.

2021-11-15 08:28 UTC, sc-ele commented
I have changed the code slightly so that the first label parameter is actually used.

Don't know why the code checks fail, don't seem to have anything to do with my code but the build environment as far as I can see.

2021-11-16 18:08 UTC, tswhison approved these changes

2021-11-16 18:08 UTC, merged