Create memory traffic generator afu test application
OPAE/opae-sdk pull request #2492
Opened 2022-02-19 00:07 UTC by kyrob

2022-02-19 00:24 UTC, r-rojo requested changes
Can you add a meaningful description to this pull request?

2022-02-19 00:45 UTC, tswhison commented on samples/mem_tg/mem_tg.cpp
> +// Copyright(c) 2020-2021, Intel Corporation
(c) date to 2022.

2022-02-19 00:45 UTC, tswhison commented on samples/mem_tg/mem_tg.h
> +// Copyright(c) 2020-2021, Intel Corporation
(c) to 2022.

2022-02-19 00:47 UTC, tswhison commented on samples/mem_tg/mem_tg.h
> +  uint32_t mem_speed_;
Probably want to init these in the constructor, even if to 0.

2022-02-19 00:49 UTC, tswhison commented on samples/mem_tg/tg_test.h
> +// Copyright(c) 2020-2021, Intel Corporation
(c) to 2022

2022-02-19 00:51 UTC, tswhison commented on samples/mem_tg/tg_test.h
> +        return status;
Or just
```c++
return run_mem_test();
```

2022-02-22 20:37 UTC, tswhison commented on opae.spec.fedora
> +%{_bindir}/mem_tg
I think maybe your branch is out-of-date with respect to the current master.  Could you rebase it?  The structure of this file, in particular, has changed last Friday.

2022-02-22 22:11 UTC, tswhison approved these changes
thanks!

2022-02-23 19:03 UTC, tswhison approved these changes

2022-02-23 19:49 UTC, r-rojo approved these changes

2022-02-23 20:10 UTC, merged