config: change 1c2c:1001 to N5011 PF
OPAE/opae-sdk pull request #2742
Opened 2022-09-28 19:07 UTC by tswhison

The previous implementation erroneously treated 1001 as the n5010 VF. Also, removes default fpga boot sequence treatment from n5010, based on feedback from Silicom.

Signed-off-by: Tim Whisonant <tim.whisonant@intel.com>

2022-09-28 19:30 UTC, anandaravuri submitted a review, later dismissed

2022-09-29 09:11 UTC, Anders5-dk requested changes
default fpga boot sequence treatment shall also be removed from n5011

2022-09-29 18:15 UTC, Anders5-dk approved these changes

2022-09-29 18:21 UTC, anandaravuri approved these changes

2022-09-29 18:22 UTC, merged